blank_issues_enabled: false  # –æ—Ç–∫–ª—é—á–∞–µ–º –ø—É—Å—Ç—ã–µ issue
contact_links: []

issue_templates:
  - name: üêû Bug report
    description: –°–æ–æ–±—â–∏ –æ–± –æ—à–∏–±–∫–µ –≤ fastyshop-backend
    labels: [bug]
    file: bug_report.yml

  - name: ‚ú® Feature request
    description: –ü—Ä–µ–¥–ª–æ–∂–∏ –Ω–æ–≤—É—é –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –∏–ª–∏ —É–ª—É—á—à–µ–Ω–∏–µ
    labels: [feature]
    file: feature_request.yml

  - name: üßπ Tech debt / Refactor
    description: –ó–∞–¥–∞—á–∏ –Ω–∞ —Ä–µ—Ñ–∞–∫—Ç–æ—Ä–∏–Ω–≥, —É–¥–∞–ª–µ–Ω–∏–µ –¥—É–±–ª–∏—Ä—É—é—â–µ–≥–æ –∫–æ–¥–∞ –∏–ª–∏ —É–ª—É—á—à–µ–Ω–∏–µ –∞—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä—ã
    labels: [tech-debt, refactor]
    file: tech_debt.yml
